  development:
    adapter: postgresql
    encoding: unicode
    database: reservester_dev
    pool: 5
    host: localhost
    port: 5432

  test:
    adapter: postgresql
    encoding: unicode
    database: reservester_test
    pool: 5
    host: localhost
    port: 5432

  production:
    adapter: postgresql
    encoding: unicode
    database: reservester_prod
    pool: 5
    host: localhost
    port: 5432